# NUMPY


In [1]:
## HOW TO CREATE NUMPY ARRAY

# 1-D ARRAY

In [2]:
import numpy as np
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

# 2-d array

In [2]:
import numpy as np
array2=np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

# HOW TO INTIALIZE THE NUMPY ARRAY OF x X y ARRAY TO 0

In [6]:
import numpy as np
ntg=np.zeros((3,4))# intializing all the element as the zeros
ntg

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# HOW TO ARRANGE NUMBERS BETWEEN X AND Y WITH AN INTERVAL OF Z

In [8]:
import numpy as np
array3=np.arange(1,10,1)
array3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# HOW TO ARRANGE Z NUMBERS BETWEEN X AND Y 

In [2]:
import numpy as np
array4=np.linspace(0,10,6)
array4

array([ 0.,  2.,  4.,  6.,  8., 10.])

# filling same number


In [3]:
import numpy as np
array5=np.full((3,2),10)
array5

array([[10, 10],
       [10, 10],
       [10, 10]])

# filling random number

In [6]:
import numpy as np
array6=np.random.random((2,3))
array6

array([[0.08386349, 0.28193461, 0.37699676],
       [0.08772433, 0.76302171, 0.1154692 ]])

# INSPECTING THE ARRAY

In [9]:
#checking size of array
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [20]:
## resize the array
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# to print the dimension of array
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
# to reshape the dimension of array
b=a.reshape(3,4,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

# finding number of elements in the array

In [10]:
a=np.arange(24)
print(a.size)

24


In [19]:
a=[1,2,3,4],[5,6,7,8]
b=np.array(a)
print(b.size)

8


# finding the data type of the array

In [22]:
a=np.arange(24)
print(a.dtype)

int32


In [23]:
a=np.arange(24,dtype='float')
print(a.dtype)

float64


# numpy array mathmatics

# addition of array

In [27]:
import numpy as np
a=[1,2,3,4,5,6]
b=np.array(a)
np.sum(a)

21

In [6]:
import numpy as np
a=[1,2,3,4,5,6],[7,8,9,10,11,12]
b=np.array(a)
np.sum(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


78

In [30]:
import numpy as np
a=[1,2,3,4,5,6],[7,8,9,10,11,12]
b=np.array(a)
np.sum(a,axis=0)## if i mention axis as 0 than it add column wise

array([ 8, 10, 12, 14, 16, 18])

In [43]:
import numpy as np
a=[1,2,3,4,5,6],[7,8,9,10,11,12]
b=np.array(a)
c=np.sum(a,axis=1)## if i mention axis as 1 than it add row wise
c

array([21, 57])

In [12]:
import numpy as np
a=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
c=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
b=np.array(a)
d=np.array(c)
np.add(b,d)

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

# Subtraction

In [9]:
import numpy as np
a=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
b=np.array(a)
np.subtract(b[0],b[1])## argumnets must be greater than 1

array([-6, -6, -6, -6, -6, -6])

In [10]:
import numpy as np
a=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
c=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
b=np.array(a)
d=np.array(c)
np.subtract(b,d)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# Multiplication

In [48]:
import numpy as np
a=[1,2,3,4,5,6],[7,8,9,10,11,12]
b=np.array(a)
np.multiply(b[0],b[1])## argumnets must be greater than 1

array([ 7, 16, 27, 40, 55, 72])

# Division

In [51]:
import numpy as np
a=[1,2,3,4,5,6],[7,8,9,10,11,12]
b=np.array(a)
c=np.divide(b[0],b[1])## argumnets must be greater than 1
c

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

# exp ,sqrt,sin,cos,log

In [5]:
import numpy as np
a=[1,2,3,4,5,6]
b=np.array(a)
print("exponent : ",np.exp(a),"\n")
print("square root : ",np.sqrt(a),"\n")
print("sin : ",np.sin(a),"\n")
print("cos: ",np.cos(a),"\n")
print("log : ",np.log(a),"\n")

exponent :  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349] 

square root :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974] 

sin :  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ] 

cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029] 

log :  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947] 



# Array comparision

In [6]:
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
np.equal(a,b)#element wise comparision

array([False, False, False])

In [7]:
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
np.array_equal(a,b)#array wise comparision

False

# aggregate function

In [9]:
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
print("sum" ,np.sum(a))
print("min" ,np.min(a))
print("max" ,np.max(a))
print("mean" ,np.mean(a))
print("correlation coefficient" ,np.median(a))
print("standard deviation" ,np.std(a))

sum 6
min 1
max 3
mean 2.0
correlation coefficient 2.0
standard deviation 0.816496580927726


# Numpy broadcasting


In [1]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b=np.array([1,2,3,4,5,6])
print(a)
print(b)
print(a+b) ## number of column or number of row must be equal otherwise it create the row of same element

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[1 2 3 4 5 6]
[[ 2  4  6  8 10 12]
 [ 8 10 12 14 16 18]]


# array manipulation

In [20]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
b=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
## concartination of array
np.concatenate((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
#stack array row wise :vertically
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
#stack array row wise :horizontally
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12]])

In [23]:
#stack array column wise:
np.column_stack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12]])

# splitting of array

In [31]:
x=np.arange(16).reshape(4,4)
print(x,"\n\n\n")
print(np.hsplit(x,2),"\n\n\n")# here it split between 1 and 2 column (column in horizontal so we represent hsplit)
print(np.vsplit(x,2),"\n\n\n")# here it split between 1 and 2 row(row in vertical so we represent vsplit)
print(np.hsplit(x,np.array([1,2,3])),"\n\n\n")## this argument represent where we want to splitt here we split at 1,2 and 3 columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 



[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] 



[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 



[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])] 





# INDEXING AND SLICING

In [32]:
## INDEXING REFERS TO POSITION.
## SLICING IS THE METHOD OF ASSCESSING PART OF DATA.


In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
## slicing the numbers 2356
a[0:2,1:]## a[row_st_index:row_end_index,column_st_index:column_end_index]

array([[2, 3],
       [5, 6]])

In [40]:
## slicing the numbers 143
a[:,0:1]

array([[1],
       [4],
       [7]])

In [41]:
## slicing the numbers 5
a[1,1]

5